
# theme:
#   name: "my_theme"
#   primary_color: "#3498db"
#   secondary_color: "#2ecc71"
#   font_family: "Arial, sans-serif"

appearance:
  mode: light
  color: emerald
  
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'ijbeasley'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''


# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Isobel Beasley 🧬"
      
      
cms:
  netlify_cms: true

icon.pack:
  ai: true

features:
  math:
    enable: true
  privacy_pack:
    enable: false

# Custom CSS/JS
custom_css: "assests/css/custom.css"
#custom_js: "/js/custom.js"