[build]
publish = "public"
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && cp _redirects.txt /opt/build/repo/public/_redirects && mv robots_prod.txt /opt/build/repo/public/robots.txt"

[build.environment]
HUGO_VERSION = "0.80.0"

[[plugins]]

package = "@netlify/plugin-sitemap"
package = "netlify-plugin-inline-critical-css"

  [plugins.inputs]
  
  fileFilter = ["*.html"]

  # A filter used to target or ignore specific directories in the publish directory. This option is passed onto the readdirp library, see https://github.com/paulmillr/readdirp#options for more info.
  directoryFilter = ["!css", "!js", "!media", "!post", "!category", "!publication_type", "!science-communication/golgi-post-introduction-to-the-golgi-for-primary-school-kids-and-beyond"]

  buildDir = "public"
  
  # change sitemap index url
  baseUrl = "https://isobelbeasley.com"

  # default change in site: 
  changeFreq =  "weekly"
  priority = 0.7
  
  prettyURLs = true
  # Append missing trailing slash to pretty URL
  trailingSlash = true


  exclude = [
  
    './.well-known/**',
    './2018/**',
    './admin/',
    '/admin.php',
    './author/**',
    'author/**',
    './author/christina-b-azodi/',
    './backup',
    './blank_type/**',
    '/blank_type/**',
    '/blank_type/**/',
    'blank_type/**',
    'blank_type/**/',
    'category/aos1/**',
    '/category/endoplasmic-reticulum/',
    '/category/organelles/',
    'category/the-relationship-between-nucleic-acids-and-proteins',
    './css/**',
    './event/**',
    './favicon.ico',
    './index.php',
    '/index.php',
    './inputs.php',
    'js/**',
    'js/vendor/reveal.js/plugin/notes/notes/**',
    './js/vendor/reveal.js/plugin/notes/**',
    '/js/vendor/reveal.js/plugin/notes/**',
    './media/**',
    '/post/**', 
    'post/**', 
    './posts/**',
    '/publication_themes/**',
    'publication_themes/**',
    './publication_themes/**',
    './Public/home/js/**',
    '**.php',
    '/**.php',
    './simple.php',
    './ss.php',
    './static/**',
    './test/**',
    './theme/**',
    './vce-biology/**/photos/',
    '.well-known/**',
    '/.well-known/**',
    './wp-content/**',
    './wp-content/plugins/**',
    './xmlrpc.php',
    './/2018/**',
    './/shop/**',
    './/test/**',
    './/xmlrpc.php',
    '**.php',
    '//**/wp-includes/**'
    
  ]
  

  
[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_prod.txt /opt/build/repo/public/robots.txt"

# netlify.toml (non-production environment)
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_non_prod.txt /opt/build/repo/public/robots.txt"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_non_prod.txt /opt/build/repo/public/robots.txt"

