[build]
publish = "public"
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && cp _redirects.txt /opt/build/repo/public/_redirects && mv robots_prod.txt /opt/build/repo/public/robots.txt"

[build.environment]
HUGO_VERSION = "0.80.0"

[[plugins]]

package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  
  buildDir = "public"
  
  # change sitemap index url
  baseUrl = "https://isobelbeasley.com"

  # default change in site: 
  changeFreq =  "monthly"
  priority = 0.7
  
  prettyURLs = true
  # Append missing trailing slash to pretty URL
  trailingSlash = true


  exclude = [           
    # Files in post subfolder (old - not used in this website)
    './posts/**',
    './publication_themes/**',
    './author/**/',
    './Public/home/js/**',
    './static/**',
    './vce-biology/**/photos/',

    './favicon.ico',
    './inputs.php',
    './simple.php',
    './ss.php',
    './/xmlrpc.php',
    
    './category/endoplasmic-reticulum/',
    './category/organelles/',
    './author/christina-b-azodi/',
    './author/',
    './wp-content/plugins/**',
    './wp-content/**',
    
    './event/**',
    './media/**',
    
    './js/**',
    './js/vendor/reveal.js/plugin/notes/notes/',
    './css/**',
    './blank_type/**/',
    './admin/',
    './blank_type/',
    './.well-known/**',
    './/2018/**',
    './/test/**',
    './/shop/**',
    '//**/wp-includes/**'

  ]
  
[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_prod.txt /opt/build/repo/public/robots.txt"

# netlify.toml (non-production environment)
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_non_prod.txt /opt/build/repo/public/robots.txt"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture && mv robots_non_prod.txt /opt/build/repo/public/robots.txt"

