---
title: 'Photosynthesis'
author: ''
date: '2021-01-24'
slug: photosynthesis
categories: ['VCE', 'Biology', 'Unit 3', 'Area of study 3']
tags: ['High school','VCE', 'Photosynthesis', 'Cellular Respiration', 'Tutoring']
subtitle: "Don't let the details overwhelm you; you need to learn less than you might think"
summary: "Let's focus on what you actually need to know on everyone's favourite VCE Biology topic (sarcasm btw)"
authors: ['Isobel Beasley']
lastmod: '2021-01-24T04:14:47+11:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<p style="font-size">

Note: This page is adapted from a learning plan + notes I used to teach online VCE summer school 2021. It's now been (mostly) adapted for the 2022-2026 VCAA study design. 
</p>


<h2 style="color:#D32F2F"> Learning Objectives </h2>

*By the end of this lesson you should be able to:* 

- List the main inputs and outputs for the light dependent and light independent stages of photosynthesis
- Explain how evidence (including chromosomal structure, double membrane, ribosome type) supports the bacterial origins of  chloroplasts
- (Bonus Easy) Agree it's ridiculous that life exists given the complexity of reactions it needs 
- (Bonus Challenge) Explain how different factors (temperature, light, glucose availability, carbon dioxide and oxygen concentration) impact the rate of cellular respiration 

<br>
<br>

<h2 style="color:#D32F2F">
Relevant VCAA 2022 Study Design Dot Points:    
</h2> 

- *inputs, outputs and locations* of the light dependent and light independent stages of photosynthesis in C3 plants (details of biochemical pathway mechanisms are not required) 
- the *role of Rubisco in photosynthesis*, including adaptations of C3, C4 and CAM plants to maximise the efficiency of photosynthesis
- the *factors that affect the rate of photosynthesis*: light availability, water availability, temperature and carbon dioxide concentration

... this looks like a lot to know - but don't worry, it's actually not at all - it's just boring.           

<br>

<h3> Important VCAA Note </h3>

> VCAA emphasises that <b> "details of the biochemical pathway mechanisms are not required" </b>

What this means that what you really need to know is: WHERE, WHAT GOES IN, and WHAT COMES OUT. Sooooo ... let's just focus on these aspects.  

<br>
<br>

<h2 style="color:#D32F2F"> 🌻 Photosynthesis </h2>

TBA ...

<h2 style="color:#D32F2F"> Extra Resources </h2>

[FreeVCEnotes.com: Energy transformations](https://freevcenotes.com/biology/notes/energy-transformations)


<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/4lWbTSpKtmtzBLykDvgpUD?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

